api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]

      # Disabling the displaying of the API documentation
      #enable_swagger_ui: false
      #enable_re_doc: true

  # Enabling only JSON-LD and JSON formats while disabling HTML format
  #formats:
   # jsonld:
    #  mime_types: ['application/ld+json']
    #json:
     # mime_types: ['application/json']